basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Peter Polacik
  description: API to manage restaurant orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Orders API
  version: "1.0"
paths:
  /health/ping:
    get:
      consumes:
      - application/json
      description: run health-check ping request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping function
      tags:
      - health
swagger: "2.0"
